/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.Disciplina;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author jemerson.reis
 */
public class telaDisciplina extends javax.swing.JFrame {
    ArrayList<Disciplina> arr = new ArrayList<Disciplina>();
    
    /**
     * Creates new form telaDisciplina
     */
    public telaDisciplina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        criarDisciplina = new javax.swing.JLabel();
        lbDisciplina = new javax.swing.JLabel();
        txDisciplina = new javax.swing.JTextField();
        lbProfessor = new javax.swing.JLabel();
        txProfessor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txIndex = new javax.swing.JTextField();
        lbIndex = new javax.swing.JLabel();
        btIndex = new javax.swing.JButton();
        lbNp1 = new javax.swing.JLabel();
        lbNp2 = new javax.swing.JLabel();
        lbSub = new javax.swing.JLabel();
        lbExame = new javax.swing.JLabel();
        lbMedia = new javax.swing.JLabel();
        txNp1 = new javax.swing.JTextField();
        txNp2 = new javax.swing.JTextField();
        txSub = new javax.swing.JTextField();
        txExame = new javax.swing.JTextField();
        txMedia = new javax.swing.JTextField();
        btMedia = new javax.swing.JButton();
        lbParaExame = new javax.swing.JLabel();
        txParaExame = new javax.swing.JTextField();
        btParaExame = new javax.swing.JButton();
        btNp1 = new javax.swing.JToggleButton();
        btNp2 = new javax.swing.JToggleButton();
        btSub = new javax.swing.JToggleButton();
        btExame = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        criarDisciplina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        criarDisciplina.setText("Criar Disciplina:");

        lbDisciplina.setText("Nome da Disciplina:");

        txDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDisciplinaActionPerformed(evt);
            }
        });

        lbProfessor.setText("Nome do professor:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIndexActionPerformed(evt);
            }
        });

        lbIndex.setText("Index");

        btIndex.setText("o");
        btIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIndexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(criarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbProfessor)
                            .addComponent(txProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txIndex)
                            .addComponent(btIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txDisciplina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDisciplina))
                        .addGap(204, 204, 204)
                        .addComponent(lbIndex)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDisciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbProfessor)
                                .addGap(10, 10, 10)
                                .addComponent(txProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(criarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbIndex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btIndex)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lbNp1.setText("NP1:");

        lbNp2.setText("NP2:");

        lbSub.setText("Sub:");

        lbExame.setText("Exame:");

        lbMedia.setText("Média:");

        txNp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNp1ActionPerformed(evt);
            }
        });

        txNp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNp2ActionPerformed(evt);
            }
        });

        txSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSubActionPerformed(evt);
            }
        });

        btMedia.setText("Calcular");
        btMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMediaActionPerformed(evt);
            }
        });

        lbParaExame.setText("Precisa no Exame:");

        txParaExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txParaExameActionPerformed(evt);
            }
        });

        btParaExame.setText("Calcular");
        btParaExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParaExameActionPerformed(evt);
            }
        });

        btNp1.setText("OK");
        btNp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNp1ActionPerformed(evt);
            }
        });

        btNp2.setText("OK");
        btNp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNp2ActionPerformed(evt);
            }
        });

        btSub.setText("OK");
        btSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubActionPerformed(evt);
            }
        });

        btExame.setText("OK");
        btExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbSub)
                                        .addGap(18, 18, 18)
                                        .addComponent(txSub, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNp2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txNp2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbExame)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txExame, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNp1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txNp1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btExame)
                                    .addComponent(btSub)
                                    .addComponent(btNp2)
                                    .addComponent(btNp1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lbMedia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btMedia))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbParaExame)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txParaExame, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btParaExame)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNp1)
                    .addComponent(txNp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNp2)
                    .addComponent(txNp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNp2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSub)
                    .addComponent(txSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbExame)
                    .addComponent(txExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExame))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbParaExame)
                    .addComponent(txParaExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btParaExame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMedia)
                    .addComponent(txMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMedia))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDisciplinaActionPerformed

    private void txNp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNp1ActionPerformed

    private void txNp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNp2ActionPerformed

    private void txSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSubActionPerformed

    private void btNp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNp1ActionPerformed
     
      int o = Integer.parseInt(txIndex.getText());
      Disciplina n1 = arr.get(o);
      if((txNp1.getText()==null) || (txNp1.getText().trim().equals(""))){
          double ff = -1;
          n1.setNp1(ff);
      } else{
        double np1 = Double.parseDouble(txNp1.getText());
        n1.setNp1(np1);
      }
       
    }//GEN-LAST:event_btNp1ActionPerformed

    private void btNp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNp2ActionPerformed
       double np2 = Double.parseDouble(txNp2.getText());
       int o = Integer.parseInt(txIndex.getText());
       Disciplina n2 = arr.get(o);
       n2.setNp2(np2);
    }//GEN-LAST:event_btNp2ActionPerformed

    private void btSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubActionPerformed
       double sub1 = Double.parseDouble(txSub.getText());
       int o = Integer.parseInt(txIndex.getText());
       Disciplina sub = arr.get(o);
       sub.setSub(sub1);
    }//GEN-LAST:event_btSubActionPerformed

    private void btExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExameActionPerformed
       double exam = Double.parseDouble(txExame.getText());
       int o = Integer.parseInt(txIndex.getText());
       Disciplina exame = arr.get(o);
       exame.setNp1(exam);
    }//GEN-LAST:event_btExameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
         String prof = txProfessor.getText();
         String discip = txDisciplina.getText(); 
         
         if((prof.length()>2) && (discip.length()>2)){
         arr.add(new Disciplina(prof, discip) );
         int ff = arr.size() - 1;
         txIndex.setText(Integer.toString(ff));
         } else{
             JOptionPane.showMessageDialog(null,"Informe um nome de professor e disciplina válidos");
         }
         
         
         
   
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIndexActionPerformed

    private void btIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIndexActionPerformed
        int o = Integer.parseInt(txIndex.getText());
        Disciplina rr = arr.get(o);
        txNp1.setText(Double.toString(rr.getNp1()));
        txNp2.setText(Double.toString(rr.getNp2()));
        
        System.out.println(arr.get(o));
    }//GEN-LAST:event_btIndexActionPerformed

    private void btParaExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParaExameActionPerformed
       int o = Integer.parseInt(txIndex.getText());
       Disciplina pex = arr.get(o);
       txParaExame.setText(Double.toString( pex.paraExame()));
    }//GEN-LAST:event_btParaExameActionPerformed

    private void txParaExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txParaExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txParaExameActionPerformed

    private void btMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMediaActionPerformed
       int o = Integer.parseInt(txIndex.getText());
       Disciplina pex = arr.get(o);
       txMedia.setText(Double.toString(pex.media()));
    }//GEN-LAST:event_btMediaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btExame;
    private javax.swing.JButton btIndex;
    private javax.swing.JButton btMedia;
    private javax.swing.JToggleButton btNp1;
    private javax.swing.JToggleButton btNp2;
    private javax.swing.JButton btParaExame;
    private javax.swing.JToggleButton btSub;
    private javax.swing.JLabel criarDisciplina;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDisciplina;
    private javax.swing.JLabel lbExame;
    private javax.swing.JLabel lbIndex;
    private javax.swing.JLabel lbMedia;
    private javax.swing.JLabel lbNp1;
    private javax.swing.JLabel lbNp2;
    private javax.swing.JLabel lbParaExame;
    private javax.swing.JLabel lbProfessor;
    private javax.swing.JLabel lbSub;
    private javax.swing.JTextField txDisciplina;
    private javax.swing.JTextField txExame;
    private javax.swing.JTextField txIndex;
    private javax.swing.JTextField txMedia;
    private javax.swing.JTextField txNp1;
    private javax.swing.JTextField txNp2;
    private javax.swing.JTextField txParaExame;
    private javax.swing.JTextField txProfessor;
    private javax.swing.JTextField txSub;
    // End of variables declaration//GEN-END:variables

 
}
